[package]
edition = "2024"
name = "eth-igb"
version = "0.1.0"

[dependencies]
dma-api = {version = "0.3", features = ["alloc"]}
log = "0.4"
mbarrier = "0.1"
thiserror = {workspace = true}

[dev-dependencies]
bare-test = "0.4"

[build-dependencies]
bare-test-macros = "0.2"

[[test]]
harness = false
name = "test"
